name:           md2html
version:        0.0.1

ghc-options: -Wall
synopsis: convert markdown to HTML and PDF

description: |
    an example how to convert an markdown file to HTML and PDF 
    with pandoc
dependencies:
  - base >= 4.7 && < 5
  - pandoc 
  - uniformBase
  - uniform-startapp
  - uniform-pandoc 
  
#   - uniform-strings
#   - uniform-convenience
# #  - test-framework 
#   - QuickCheck
#   - HTF

library:
  source-dirs: .

executables:
  md2:
    main: md2html.hs
    source-dirs: app
    dependencies: 
      - md2html

# tests:
#   test1:
#     main: ExampleTesting.hs
#     source-dirs: tests
#     dependencies: 
#       - TestSimple
# #      - QuickCheck 
# #      - test-framework 

